"""Audit intake: the data collection pack handed over at the start of an audit.

Every connector declares the exports it reads (:class:`~trailguide.connectors.base.IntakeSheet`),
so the collection template is generated from the code that actually parses the
data. A column cannot drift out of the template without the connector changing
too, which is the failure this is designed to prevent - a pack that asks for
columns nothing reads, or omits columns everything needs.

The pack is three things:

* a workbook with one tab per export, ready to paste exports into,
* a config wired to the CSVs that workbook produces,
* a README explaining what each export unlocks and where to get it.

The workbook needs ``openpyxl``; the CSV stubs, config and README do not. Core
stays dependency-free so the engine still runs anywhere with only PyYAML.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .connectors import registered_connectors
from .connectors.base import INTAKE_PRIORITIES, IntakeSheet
from .errors import TrailGuideError

#: Why each priority band exists, shown in the pack so the ask is proportionate.
PRIORITY_NOTES = {
    "core": "Collect first. Without these most of the analysis has nothing to work on.",
    "recommended": "Collect if available. Each one materially sharpens the projections.",
    "optional": "Nice to have. Each adds a surface but nothing else depends on it.",
}


def intake_sheets() -> list[IntakeSheet]:
    """Every declared export, ordered by priority then title."""
    sheets: list[IntakeSheet] = []
    for connector in registered_connectors():
        sheets.extend(connector.intake)

    def sort_key(sheet: IntakeSheet) -> tuple[int, str]:
        try:
            band = INTAKE_PRIORITIES.index(sheet.priority)
        except ValueError:
            band = len(INTAKE_PRIORITIES)
        return (band, sheet.title)

    return sorted(sheets, key=sort_key)


@dataclass
class ClientProfile:
    """The handful of facts an audit cannot be run without."""

    name: str = "Example Client"
    domain: str = "example.com"
    brand_terms: tuple[str, ...] = ()
    competitors: tuple[str, ...] = ()
    economics_model: str = "b2b"
    currency: str = "USD"
    revenue_target: float = 0.0

    @property
    def slug(self) -> str:
        cleaned = "".join(
            char if char.isalnum() else "-" for char in self.name.lower()
        ).strip("-")
        while "--" in cleaned:
            cleaned = cleaned.replace("--", "-")
        return cleaned or "client"


# -- CSV stubs and config -------------------------------------------------


def write_csv_stubs(directory: str | Path, sheets: list[IntakeSheet] | None = None) -> list[Path]:
    """Write a header-only CSV per export, for teams that would rather not use a workbook."""
    out_dir = Path(directory)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for sheet in sheets if sheets is not None else intake_sheets():
        target = out_dir / sheet.filename
        with target.open("w", encoding="utf-8", newline="") as handle:
            csv.writer(handle).writerow(sheet.headers)
        written.append(target)
    return written


def render_config(
    profile: ClientProfile,
    data_dir: str = "data",
    sheets: list[IntakeSheet] | None = None,
) -> str:
    """Render a client config wired to the intake pack's CSV filenames.

    Every declared export is listed, including ones not yet collected, with the
    uncollected ones disabled rather than deleted - so switching a source on is
    a one-word edit once its export arrives.
    """
    sheets = sheets if sheets is not None else intake_sheets()
    brand = ", ".join(profile.brand_terms) or profile.domain.split(".")[0]
    competitors = ", ".join(profile.competitors)

    lines = [
        f"# Trail Guide configuration for {profile.name}.",
        "#",
        "# Generated by `trailguide intake`. Every number below is an assumption the",
        "# analysis is built on - review them with the client before trusting output.",
        "",
        "client:",
        f"  name: {profile.name}",
        f"  domain: {profile.domain}",
        f"  brand_terms: [{brand}]",
        f"  competitors: [{competitors}]",
        "",
        "planning:",
        "  horizon_months: 12",
        "  quarters: 4",
        f"  currency: {profile.currency}",
        f"  revenue_target: {profile.revenue_target:.0f}",
        "  baseline_organic_revenue: 0",
        "",
        "economics:",
        f"  model: {profile.economics_model}",
        "  gross_margin: 0.80",
    ]

    if profile.economics_model == "ecommerce":
        lines += [
            "  ecommerce:",
            "    conversion_rate: 0.021",
            "    average_order_value: 120",
        ]
    else:
        lines += [
            "  b2b:",
            "    visit_to_lead: 0.022",
            "    lead_to_mql: 0.45",
            "    mql_to_sql: 0.40",
            "    sql_to_win: 0.22",
            "    average_contract_value: 24000",
            "    sales_cycle_days: 75",
        ]

    lines += [
        "",
        "capacity:",
        "  reserved_for_enabling: 0.10",
        "  per_quarter:",
        "    seo: 45",
        "    content: 60",
        "    engineering: 20",
        "    design: 15",
        "    analytics: 10",
        "    strategy: 8",
        "    outreach: 10",
        "",
        "sources:",
    ]

    for sheet in sheets:
        lines.append(f"  # {sheet.title} - {sheet.priority}")
        lines.append(f"  - type: {sheet.source_type}")
        lines.append(f"    name: {sheet.key}")
        lines.append(f"    path: {data_dir}/{sheet.filename}")
        if sheet.priority != "core":
            lines.append("    enabled: true      # set false until this export is collected")
        lines.append("")

    lines += [
        "analysis:",
        "  defaults: {}",
        "  settings:",
        "    dark_traffic:",
        "      # 12 = the keyword export covers one month. Change it to match your window.",
        "      keyword_periods_per_year: 12",
        "",
    ]
    return "\n".join(lines)


def render_readme(profile: ClientProfile, sheets: list[IntakeSheet] | None = None) -> str:
    """Render the collection brief that travels with the pack."""
    sheets = sheets if sheets is not None else intake_sheets()
    lines = [
        f"# Audit data intake - {profile.name}",
        "",
        "Everything the analysis reads, in one pack. Fill the workbook tabs (or drop",
        "CSVs into `data/`), then run the audit.",
        "",
        "```bash",
        f"trailguide validate --config {profile.slug}.yml   # confirms every export parses",
        f"trailguide run --config {profile.slug}.yml --out ./out",
        "```",
        "",
        "`validate` is the one to run first: it reports, per source, how many records",
        "loaded and why any failed. A source that fails degrades the run rather than",
        "ending it, so check the coverage table before trusting the output.",
        "",
        "## What to collect",
        "",
        "| Export | Priority | Where it comes from | What it unlocks |",
        "| --- | --- | --- | --- |",
    ]
    for sheet in sheets:
        export_from = sheet.export_from.replace("\n", " ")
        unlocks = sheet.unlocks.replace("\n", " ") or "-"
        lines.append(
            f"| `{sheet.filename}` | {sheet.priority} | {export_from} | {unlocks} |"
        )

    lines += ["", "## Priorities", ""]
    for priority in INTAKE_PRIORITIES:
        if any(sheet.priority == priority for sheet in sheets):
            lines.append(f"- **{priority}** - {PRIORITY_NOTES.get(priority, '')}")

    lines += [
        "",
        "## Two things that are easy to get wrong",
        "",
        "1. **Keep the date windows aligned.** The GA4 and Search Console exports should",
        "   cover the same period. If the keyword export is not one month, change",
        "   `analysis.settings.dark_traffic.keyword_periods_per_year` to match - the",
        "   other estimators are annual, and mixing bases silently skews the blend.",
        "2. **Column names are flexible, columns are not.** Matching ignores case and",
        "   separators, so `Search Volume`, `search_volume` and `searchvolume` are the",
        "   same column. But a column that is not there cannot be inferred - check the",
        "   `validate` coverage table rather than assuming.",
        "",
        "## Notes per export",
        "",
    ]
    for sheet in sheets:
        if not sheet.notes:
            continue
        lines.append(f"**{sheet.title}** - {sheet.notes}")
        lines.append("")

    return "\n".join(lines)


# -- Workbook -------------------------------------------------------------

#: Fill colours per priority band, so the ask reads at a glance.
_PRIORITY_FILL = {
    "core": "FFC9DAF8",
    "recommended": "FFD9EAD3",
    "optional": "FFF3F3F3",
}
_HEADER_FILL = "FF1F3864"
_REQUIRED_FILL = "FFFFF2CC"


def _require_openpyxl() -> Any:
    try:
        import openpyxl  # noqa: PLC0415 - optional dependency, imported on use
    except ImportError as exc:  # pragma: no cover - exercised only without the extra
        raise TrailGuideError(
            "the intake workbook needs openpyxl. Install it with:\n"
            '    pip install "trailguide[deliverables]"\n'
            "Or pass --no-workbook to write the CSV stubs, config and README only."
        ) from exc
    return openpyxl


def write_workbook(
    path: str | Path,
    profile: ClientProfile,
    sheets: list[IntakeSheet] | None = None,
) -> Path:
    """Write the intake workbook: a guide, a client profile and one tab per export.

    Data tabs are left empty on purpose. An example row is the kind of thing
    that survives into a real audit and quietly corrupts it, so the worked
    examples live on the reference tab instead, where they cannot be mistaken
    for data.
    """
    openpyxl = _require_openpyxl()
    from openpyxl.comments import Comment
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    sheets = sheets if sheets is not None else intake_sheets()
    workbook = openpyxl.Workbook()

    def style_header(worksheet: Any, row: int = 1) -> None:
        for cell in worksheet[row]:
            if cell.value is None:
                continue
            cell.font = Font(bold=True, color="FFFFFFFF")
            cell.fill = PatternFill("solid", fgColor=_HEADER_FILL)
            cell.alignment = Alignment(vertical="center", wrap_text=True)

    def autosize(worksheet: Any, widths: dict[int, int]) -> None:
        for index, width in widths.items():
            worksheet.column_dimensions[get_column_letter(index)].width = width

    # -- Start here -------------------------------------------------------
    guide = workbook.active
    guide.title = "Start here"
    guide["A1"] = f"Audit data intake - {profile.name}"
    guide["A1"].font = Font(size=16, bold=True)
    guide["A2"] = (
        "One tab per export. Paste each export under its headers, keeping row 1 as is. "
        "Blank tabs are fine - the analysis degrades to what it has and tells you what "
        "went missing."
    )
    guide["A2"].alignment = Alignment(wrap_text=True, vertical="top")
    guide.merge_cells("A2:F2")
    guide.row_dimensions[2].height = 42

    headers = ["Tab", "Priority", "Source type", "Where to export it from",
               "What it unlocks", "Collected?"]
    for column, title in enumerate(headers, start=1):
        guide.cell(row=4, column=column, value=title)
    style_header(guide, row=4)

    for offset, sheet in enumerate(sheets):
        row = 5 + offset
        guide.cell(row=row, column=1, value=sheet.title)
        priority_cell = guide.cell(row=row, column=2, value=sheet.priority)
        priority_cell.fill = PatternFill(
            "solid", fgColor=_PRIORITY_FILL.get(sheet.priority, "FFFFFFFF")
        )
        guide.cell(row=row, column=3, value=sheet.source_type)
        guide.cell(row=row, column=4, value=sheet.export_from).alignment = Alignment(
            wrap_text=True, vertical="top"
        )
        guide.cell(row=row, column=5, value=sheet.unlocks).alignment = Alignment(
            wrap_text=True, vertical="top"
        )
        guide.cell(row=row, column=6, value="no")
        guide.row_dimensions[row].height = 46

    notes_row = 6 + len(sheets)
    guide.cell(row=notes_row, column=1, value="Priority key").font = Font(bold=True)
    for offset, priority in enumerate(INTAKE_PRIORITIES, start=1):
        guide.cell(row=notes_row + offset, column=1, value=priority).fill = PatternFill(
            "solid", fgColor=_PRIORITY_FILL.get(priority, "FFFFFFFF")
        )
        guide.cell(row=notes_row + offset, column=2, value=PRIORITY_NOTES.get(priority, ""))
    autosize(guide, {1: 34, 2: 15, 3: 17, 4: 54, 5: 54, 6: 13})
    guide.freeze_panes = "A5"

    # -- Client profile ---------------------------------------------------
    client = workbook.create_sheet("Client profile")
    client["A1"] = "Field"
    client["B1"] = "Value"
    client["C1"] = "Notes"
    style_header(client)
    profile_rows = [
        ("Client name", profile.name, "Used in the report title."),
        ("Domain", profile.domain, "Primary domain, no protocol."),
        ("Brand terms", ", ".join(profile.brand_terms),
         "Comma separated. Drives branded/non-branded splits - get this right."),
        ("Competitors", ", ".join(profile.competitors),
         "Comma separated domains. Must match the keyword gap column headers."),
        ("Economics model", profile.economics_model, "b2b or ecommerce."),
        ("Currency", profile.currency, "ISO code."),
        ("Revenue target", profile.revenue_target or "",
         "Incremental revenue the roadmap must deliver inside the horizon."),
        ("Horizon months", 12, "Planning horizon."),
        ("Gross margin", 0.80, "Used for gross profit reporting."),
        ("Keyword export window", "1 month",
         "If not one month, update keyword_periods_per_year in the config."),
    ]
    for offset, (field_name, value, note) in enumerate(profile_rows, start=2):
        client.cell(row=offset, column=1, value=field_name).font = Font(bold=True)
        client.cell(row=offset, column=2, value=value)
        client.cell(row=offset, column=3, value=note)
    autosize(client, {1: 24, 2: 34, 3: 72})
    client.freeze_panes = "A2"

    # -- Column reference -------------------------------------------------
    reference = workbook.create_sheet("Column reference")
    for column, title in enumerate(
        ["Tab", "Column", "Required", "Description", "Example"], start=1
    ):
        reference.cell(row=1, column=column, value=title)
    style_header(reference)
    row = 2
    for sheet in sheets:
        for column_spec in sheet.columns:
            reference.cell(row=row, column=1, value=sheet.title)
            reference.cell(row=row, column=2, value=column_spec.name)
            required_cell = reference.cell(
                row=row, column=3, value="required" if column_spec.required else "optional"
            )
            if column_spec.required:
                required_cell.fill = PatternFill("solid", fgColor=_REQUIRED_FILL)
            reference.cell(row=row, column=4, value=column_spec.description)
            reference.cell(row=row, column=5, value=column_spec.example)
            row += 1
    autosize(reference, {1: 30, 2: 30, 3: 12, 4: 62, 5: 34})
    reference.freeze_panes = "A2"

    # -- One tab per export ----------------------------------------------
    for sheet in sheets:
        worksheet = workbook.create_sheet(_tab_name(sheet, workbook.sheetnames))
        for column, column_spec in enumerate(sheet.columns, start=1):
            cell = worksheet.cell(row=1, column=column, value=column_spec.name)
            note = [column_spec.description]
            if column_spec.example:
                note.append(f"Example: {column_spec.example}")
            note.append("Required." if column_spec.required else "Optional.")
            cell.comment = Comment("\n".join(note), "Trail Guide")
            if column_spec.required:
                cell.fill = PatternFill("solid", fgColor=_HEADER_FILL)
        style_header(worksheet)
        autosize(worksheet, {index: 22 for index in range(1, len(sheet.columns) + 1)})
        worksheet.freeze_panes = "A2"

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(target)
    return target


def _tab_name(sheet: IntakeSheet, taken: list[str]) -> str:
    """Excel caps tab names at 31 characters and forbids a few punctuation marks."""
    cleaned = sheet.title
    for char in "[]:*?/\\":
        cleaned = cleaned.replace(char, "-")
    cleaned = cleaned[:31].strip()
    if cleaned not in taken:
        return cleaned
    for suffix in range(2, 100):
        candidate = f"{cleaned[:28]} {suffix}"
        if candidate not in taken:
            return candidate
    return sheet.key[:31]


def read_workbook(path: str | Path, directory: str | Path) -> list[Path]:
    """Split a filled intake workbook back into the CSVs the connectors read.

    Tabs are matched to exports by their headers rather than their names, so a
    renamed tab still lands in the right place. Empty tabs are skipped, which is
    what makes a partially filled pack runnable.
    """
    openpyxl = _require_openpyxl()

    sheets = intake_sheets()
    by_signature = {_signature(sheet.headers): sheet for sheet in sheets}
    by_title = {sheet.title: sheet for sheet in sheets}

    workbook = openpyxl.load_workbook(path, data_only=True, read_only=True)
    out_dir = Path(directory)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for worksheet in workbook.worksheets:
        rows = worksheet.iter_rows(values_only=True)
        try:
            header_row = next(rows)
        except StopIteration:
            continue
        headers = [str(value).strip() for value in header_row if value is not None]
        if not headers:
            continue

        sheet = by_signature.get(_signature(headers)) or by_title.get(worksheet.title)
        if sheet is None:
            continue

        data = [row for row in rows if any(value not in (None, "") for value in row)]
        if not data:
            continue

        target = out_dir / sheet.filename
        with target.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(headers)
            for row in data:
                writer.writerow(
                    ["" if value is None else value for value in row[: len(headers)]]
                )
        written.append(target)

    workbook.close()
    return written


def _signature(headers: list[str]) -> tuple[str, ...]:
    """Normalize a header row so tab matching survives case and separator drift."""
    return tuple(
        sorted(
            "".join(char for char in str(header).lower() if char.isalnum())
            for header in headers
            if str(header).strip()
        )
    )


# -- reading the filled profile back out ----------------------------------

#: Client profile tab label -> (config block, key). The workbook is where the
#: client answers these, so this is what carries their answers into the config.
PROFILE_FIELDS = {
    "client name": ("client", "name"),
    "domain": ("client", "domain"),
    "brand terms": ("client", "brand_terms"),
    "competitors": ("client", "competitors"),
    "economics model": ("economics", "model"),
    "currency": ("planning", "currency"),
    "revenue target": ("planning", "revenue_target"),
    "horizon months": ("planning", "horizon_months"),
    "gross margin": ("economics", "gross_margin"),
}

#: Fields written back as YAML inline lists rather than scalars.
_LIST_FIELDS = {"brand_terms", "competitors"}


def read_profile(path: str | Path) -> dict[tuple[str, str], str]:
    """Read the workbook's client profile tab into ``{(block, key): value}``.

    Only fields the client actually filled in are returned, so a blank cell
    leaves whatever the config already says rather than clearing it.
    """
    openpyxl = _require_openpyxl()
    workbook = openpyxl.load_workbook(path, data_only=True, read_only=True)
    found: dict[tuple[str, str], str] = {}

    for worksheet in workbook.worksheets:
        if worksheet.title.strip().lower() != "client profile":
            continue
        for row in worksheet.iter_rows(min_row=2, max_col=2, values_only=True):
            if not row or row[0] is None:
                continue
            target = PROFILE_FIELDS.get(str(row[0]).strip().lower())
            value = row[1] if len(row) > 1 else None
            if target and value not in (None, ""):
                found[target] = str(value).strip()
    workbook.close()
    return found


def apply_profile(config_text: str, profile: dict[tuple[str, str], str]) -> tuple[str, list[str]]:
    """Update a generated config in place from profile values.

    Rewrites the matching scalar lines rather than reserializing the document,
    because the generated config carries comments explaining every assumption and
    a YAML round trip would strip them.

    Returns the new text and a list of the changes made, for reporting.
    """
    if not profile:
        return config_text, []

    lines = config_text.splitlines()
    block = ""
    changes: list[str] = []

    for index, line in enumerate(lines):
        if line and not line[0].isspace() and line.rstrip().endswith(":"):
            block = line.split(":", 1)[0].strip()
            continue
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        # Only touch keys nested one level under a known top-level block.
        indent = len(line) - len(line.lstrip())
        if indent != 2:
            continue
        key = stripped.split(":", 1)[0].strip()
        value = profile.get((block, key))
        if value is None:
            continue

        if key in _LIST_FIELDS:
            items = [part.strip() for part in value.split(",") if part.strip()]
            rendered = "[" + ", ".join(items) + "]"
        elif key in ("revenue_target", "horizon_months"):
            try:
                rendered = f"{float(value):.0f}"
            except ValueError:
                continue
        elif key == "gross_margin":
            try:
                rendered = f"{float(value):g}"
            except ValueError:
                continue
        else:
            rendered = value

        # Keep any trailing comment: it usually explains the assumption.
        comment = f"      # {line.split('#', 1)[1].strip()}" if "#" in line else ""
        previous = stripped.split(":", 1)[1].strip().split("#")[0].strip()
        if previous != rendered:
            changes.append(f"{block}.{key}: {previous or '(empty)'} -> {rendered}")
        lines[index] = f"  {key}: {rendered}{comment}"

    return "\n".join(lines) + "\n", changes
